name: Test with Razd

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: razd-cli/razd-action-mise@v1
        with:
          mise-version: latest

      - name: Install and verify
        run: |
          razd --version
          razd install --yes
          razd dev